### ISSUE TITLE
Suggest new site: truyenvkl.com

### ISSUE THREAD

**Issue by lelinhtinh** [nntoan/UserScripts#1]
Trước code không có hệ thống rõ ràng, giờ thêm trang mới rắc rối quá, bác giúp hộ được không? 😔 
https://github.com/lelinhtinh/Userscript/issues/56

**Comment by nntoan** [comment]
Ok không vấn đề gì! Bác còn cần nữa không để tôi code choa :D @lelinhtinh

**Comment by lelinhtinh** [comment]
Nếu được thì tốt quá 👍 
Hôm đó close, định làm [script tải tổng hợp](https://github.com/lelinhtinh/Userscript/blob/master/novel_downloader/novel_downloader.user.js) rồi quên mất 😆

**Comment by nntoan** [comment]
Vui lòng theo dõi ticket #7 . Thân.
