### ISSUE TITLE
bachngocsachdownloader bị lỗi

### ISSUE THREAD

**Issue by hianalyst** [nntoan/UserScripts#2]
Hi bác, 
dạo này e dùng thử trên bachngocsach thì script bác viết nó toàn báo lỗi underfield j j đó, liệu bác có thể fix hộ em được k ạ?

**Comment by nntoan** [comment]
Issue này fix rồi bạn nhé, bạn update lên version mới nhất là ok.

**Comment by hianalyst** [comment]
tks bác nhìu nhìu hôm bữa thấy mail báo mà đang trong phòng thi nên ko cảm ơn kịp 💯 
chúc bác một ngày tốt lành ạ
